version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    image: dinopedia
    environment:
      APP_DEBUG_MODE: "True"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: dinopedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
      DJANGO_SUPERUSER_PASSWORD: admin
    entrypoint: ""
    # command: "python dinopedia/manage.py runserver 0.0.0.0:8000"
    command: bash -c "python dinopedia/manage.py makemigrations && 
            python dinopedia/manage.py migrate &&  
            python dinopedia/manage.py runserver 0.0.0.0:8000" 
            # run this only the first time before runserver
            # python dinopedia/manage.py createsuperuser --noinput && 

    ports:
      - 8000:8000
    volumes:
      - ./dinopedia:/usr/dinopedia/app/dinopedia
      - ./tests:/usr/dinopedia/app/tests
      - ./pyproject.toml:/usr/dinopedia/app/pyproject.toml
      - ./poetry.lock:/usr/dinopedia/app/poetry.lock
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: dinopedia
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
