version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    image: dinopedia
    environment:
      APP_DEBUG_MODE: "True"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: dinopedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
      DJANGO_SUPERUSER_PASSWORD: admin
    entrypoint: ""
    # command: "python dinopedia/manage.py runserver 0.0.0.0:8000"
    command: bash -c "
            python dinopedia/manage.py migrate &&
            python dinopedia/manage.py runserver 0.0.0.0:8000"
            # if you do not have migrations run this first
            # python dinopedia/manage.py makemigrations --noinput &&  
            # run this only the first time before runserver
            # python dinopedia/manage.py createsuperuser --noinput &&

    ports:
      - 8000:8000
    volumes:
    # had to uncomment this because it was loading dinopedia with own:group -> 1000:1000
    # and could not find a workaround
      # - ./dinopedia:/usr/dinopedia/app/dinopedia
      # - ./tests:/usr/dinopedia/app/tests
      - ./pyproject.toml:/usr/dinopedia/app/pyproject.toml
      - ./poetry.lock:/usr/dinopedia/app/poetry.lock
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: dinopedia
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - dinopedia_data:/var/lib/postgresql/data
      - dinopedia_backups:/pg_backups

volumes:
  dinopedia_data: {}
  dinopedia_backups: {} 