# Generated by Django 4.0.6 on 2022-07-23 12:42

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0002_period_period_unique_period_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinoSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('TN', 'Tiny'), ('VS', 'Very small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('VL', 'Very large'), ('G', 'Gigantic')], max_length=15)),
                ('length_min', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)])),
                ('length_max', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)])),
                ('height_min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('height_max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('width_min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('width_max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('weight_min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('weight_max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
            ],
            options={
                'ordering': ['height_min'],
            },
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.UniqueConstraint(fields=('size',), name='unique_dino_size'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('length_max__gt', django.db.models.expressions.F('length_min'))), name='max_length_gt_min'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('height_max__gt', django.db.models.expressions.F('height_min'))), name='max_height_gt_min'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('width_max__gt', django.db.models.expressions.F('width_min'))), name='max_width_gt_min'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('weight_max__gt', django.db.models.expressions.F('weight_min'))), name='max_weight_gt_min'),
        ),
    ]
