# Generated by Django 4.0.6 on 2022-07-23 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0003_dinosize_dinosize_unique_dino_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosize',
            name='height_max',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.001)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dinosize',
            name='height_min',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.001)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dinosize',
            name='length_max',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='dinosize',
            name='length_min',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
