# Generated by Django 4.0.6 on 2022-07-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0004_alter_dinosize_height_max_alter_dinosize_height_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eating', models.CharField(choices=[('C', 'Carnivore'), ('H', 'Herbivore'), ('O', 'Omnivore')], max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['eating'],
            },
        ),
        migrations.AddConstraint(
            model_name='eatingtype',
            constraint=models.UniqueConstraint(fields=('eating',), name='unique_eating_type'),
        ),
    ]
