# Generated by Django 4.0.6 on 2022-07-23 13:10

import dinosaurs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0005_eatingtype_eatingtype_unique_eating_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(default='img1.jpg', upload_to=dinosaurs.models.image_directory_path)),
                ('image2', models.ImageField(default='img2.jpg', upload_to=dinosaurs.models.image_directory_path)),
                ('eating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dinosaurs.eatingtype')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dinosaurs.period')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dinosaurs.dinosize')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='dinosaur',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_dinosaur_name'),
        ),
    ]
