# Generated by Django 4.0.6 on 2022-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0006_dinosaur_dinosaur_unique_dinosaur_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
