# Generated by Django 4.0.6 on 2022-07-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0008_dinosaur_typical_colours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
