# Generated by Django 4.0.6 on 2022-07-24 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0010_alter_eatingtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosize',
            name='height_max',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='dinosize',
            name='height_min',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
