# Generated by Django 4.0.6 on 2022-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0011_alter_dinosize_height_max_alter_dinosize_height_min'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('length_max__gte', 0)), name='lenght_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('length_min__gte', 0)), name='lenght_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('height_max__gte', 0)), name='height_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('height_min__gte', 0)), name='height_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('width_max__gte', 0)), name='width_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('width_min__gte', 0)), name='width_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('weight_max__gte', 0)), name='weight_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='dinosize',
            constraint=models.CheckConstraint(check=models.Q(('weight_min__gte', 0)), name='weight_min_positive'),
        ),
    ]
