# Generated by Django 4.0.6 on 2022-07-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0012_dinosize_lenght_max_positive_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DinoOwner',
        ),
    ]
