# Generated by Django 4.0.6 on 2022-07-25 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0014_petdinosaur_dinoowner_petdinosaur_unique_name_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinoowner',
            name='petDino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dinosaurs.petdinosaur'),
        ),
    ]
